# .github/FUNDING.yml

support:
  heading: "Support"
  blurb: "If this product saves you time, consider supporting the project:"
  links:

github: [TrishulaSoftware]
ko_fi: trishulasoftware
buy_me_a_coffee: trishulasoftware
open_collective: trishula-software
patreon: TrishulaSoftware
